### ISSUE TITLE
Test suite is not reliable

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiodocker#52] opened 2017-06-28 18:06 UTC
See https://travis-ci.org/aio-libs/aiodocker/jobs/248039891
Next run will be successful, sure.

Could we fix it?
Any ideas?

**Comment by barrachri** [comment] 2017-06-28 18:28
That is specifically to `docker swarm leave -f`, I am quite sure is a bug of docker but sadly the error message is not very helpful.

**Comment by asvetlov** [comment] 2017-06-28 18:32
Could you add a workaround?
Say if the call failed -- catch exception and convert it by `pytest.xfail` to message which doesn't stop CI but reports a warning?

**Comment by barrachri** [comment] 2017-07-06 15:43
I think we can close this.

**Comment by barrachri** [comment] 2017-07-07 16:54
fixed by https://github.com/aio-libs/aiodocker/pull/54

**Comment by barrachri** [comment] 2017-07-07 19:36
I just checked, we are running tests only with Python 3.6.1.......

The docker-compose file is fixed and we use it to run the tests.

**Comment by barrachri** [comment] 2017-07-21 10:59
Closing, resolved with the last commits.

**Comment by cecton** [comment] 2017-08-04 12:15
@barrachri can you provide me the links to the tickets opened at Docker? Also if you don't mind I would like to keep an issue here opened somewhere because a temporary fix is not a solution. Right now it looks like everything is alright but it isn't and people will try to search for the problem here first.

**Comment by barrachri** [comment] 2017-08-04 12:33
Hello @cecton, you can check here https://github.com/moby/moby/issues/29987.
It's not really a fix, more like the test __can__ fail. But if you check the last PRs it was always an __xpassed__.

**Comment by cecton** [comment] 2017-08-04 12:51
Thanks @barrachri ... hmmm.... yes I think they fixed it in 17.06 but I can easily reproduce it on all older versions. I don't think they plan to fix it for the older versions though, it's tagged as an enhancement.

**Comment by barrachri** [comment] 2018-02-11 11:25
Fixed.

**Closed by barrachri** 2018-02-11 11:25 UTC
Labels: bug
